version: "3.0"
 
services:
  bot:
    image: bundles_checker_bot:1.0.1
    build: ./bot
    command: python bot.py
    volumes:
      - /bot
    env_file:
      - ./.env.bot.dev
  web:
    image: bundles_checker_web:1.0.1
    build: .
    command: gunicorn bundles_checker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/bundles_checker
    expose:
      - 8000
    env_file:
    - ./.env.dev
  nginx:
    build: ./nginx
    ports:
      - 84:80
    depends_on:
      - web