# Generated by Django 4.0 on 2021-12-10 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_folder', models.CharField(max_length=255, verbose_name='Название папки')),
                ('current_folder', models.BooleanField(verbose_name='Текущая папка')),
            ],
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, verbose_name='Название приложения')),
                ('date', models.DateTimeField(verbose_name='Последнее обновление')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.folders')),
            ],
        ),
    ]
