# Generated by Django 4.0 on 2021-12-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_apps_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='status',
            field=models.CharField(default='Не опубликовано', max_length=255, verbose_name='Статус'),
        ),
    ]
