# Generated by Django 4.0 on 2021-12-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_apps_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folders',
            name='current_folder',
        ),
        migrations.AlterField(
            model_name='apps',
            name='date',
            field=models.CharField(max_length=50, verbose_name='Последнее обновление'),
        ),
    ]
