# Generated by Django 4.0 on 2021-12-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_folders_current_folder_alter_apps_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps',
            old_name='date',
            new_name='time',
        ),
    ]
