# Generated by Django 4.0 on 2021-12-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_date_apps_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='start_time',
            field=models.CharField(default='None', max_length=50, verbose_name='Дата/время добавления'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='name_folder',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название папки'),
        ),
    ]
