# Generated by Django 4.0 on 2021-12-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_folders_current_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='date',
            field=models.DateTimeField(default=None, verbose_name='Последнее обновление'),
        ),
    ]
