# Generated by Django 4.0.2 on 2022-02-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_time_apps_last_time_apps_next_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='app_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название приложения'),
        ),
    ]
