# Generated by Django 4.0.2 on 2022-02-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_apps_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='last_update',
            field=models.CharField(max_length=50, null=True, verbose_name='Обновление приложения'),
        ),
    ]
