# Generated by Django 4.0.2 on 2022-02-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_apps_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='last_update',
            field=models.CharField(default='Не существует', max_length=50, verbose_name='Обновление приложения'),
        ),
    ]
